### ISSUE TITLE
bug reports

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#12] opened 2021-05-29 02:48 UTC
hi

I'm  a big fan of your work and want to test each release and report bugs!
Unfortunately i'm too shy to chat on discord.
Is it possible to make a sticky thread on the forum about how to install and setup 3darcade alpha correctly? And how the current features work or maybe the youtube videos are all current features?
You can then update/change this for each new release and everybody who wants to test can read it.
Not a complete manual, just installation and basic usage (video links of youtube).

Some questions:
- where to report bugs? Maybe better here or on the forum? I thought here is better for dev purposes?
 
- is windows 7 supported? I have a i7 16 gb with gtx 1070 on win 10 and i5 4 gb with gt 220 on win 7 to test. So a quite good and slow pc to do benchmarks. Do you have interest in benchmarks ?

- is it possible for each new release to make a new video with changes or new features? In this way I can test exactly the new ones

thx a lot for the great work!

**Comment by dreamsoftunitedkingdom** [comment] 2021-05-29 02:49
I closed my previous questions which are answered or understood by me so you can only look at the open issues more easy.

**Comment by Skurdt** [comment] 2021-05-29 05:40
We've never done voice chat on discord. I'd rather you ask some of these questions on the text channel on discord rather than adding more "issues" here.

Installing is just unzipping the release somewhere and running the exe.

The forum contains posts that describe all of the basic constructs of the program (aka. the scenes, platforms, emulators and game lists).
However, these are mostly conceptual. In the sense that the runtime (and UI) interacts with these, but can display them differently depending on contexts.

If using the program and navigating the different states with the UI is not easily understandable. Then there might be some design flaws on my part.
Either this is a good approach or not, I think that by trying to figure out some of the stuff without a guide, then giving feedback like "this panel is too confusing because of <xyz>" or "this button doesn't do what I expect, which is <xyz>" is much more helpful for the project.
As opposed to going through a complicated set of steps from a manual to get the basics working and then assume that these particular features/things are in a good state when only understood by a single or couple of persons.

Keep in mind that it's marked as alpha also for these reasons too (other than expected bugs).
The current features set is relatively narrow, as development continues and features are added over time, I expect to keep a relatively sane level of complexity on the user's side.
A lot of frontends started with basic features that where easy to setup, and then became way too complicated for a new user arriving years later...

**Comment by Skurdt** [comment] 2021-05-29 05:59
For bugs and issues, GitHub issues are the perfect place for these, if formatted correctly...

Example:
- Title: Save button on Emulators panel problem
- Description: Clicking the save button in the emulators panel doesn't reactivate user input but the cancel button does.

Then you can add more details, preferably the steps to reproduce the problem and even screenshots or videos of the issue.

For windows 7 I have no idea, if the unity version used for the build supports it, then it should work...

As far as benchmarks go, it's hard to tell right now because there's no minimum spec defined (this is on purpose, I don't have all the proper assets needed to define this yet and I don't want to set a performance barrier at this time).
But you're welcome to describe whatever you feel is a performance problem/concern on a particular setup.

**Comment by dreamsoftunitedkingdom** [comment] 2021-05-29 19:08
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA

**Closed** 2021-05-29 19:28 UTC
